---
title: "CHAPTER 5: Exploratory Data Analysis"
author: "Trevor Barnes"
date: "11/16/2017"
output: html_document
runtime: shiny
---
# Chapter 5 - Exploratory Data Analysis

```{r include=FALSE}
library(tidyverse)
library(hexbin)
library(modelr)
```
## VISUALIZING DISTRIBUTIONS

```{r}
## Plot the data of diamonds and make a bar chart by cut

ggplot(data=diamonds) +
  geom_bar(mapping = aes(x = cut))

## Count the number by cut

diamonds %>%
  count(cut)

## Make a histogram with a binwidth of .5 with carat along the x-axis

ggplot(data = diamonds) +
  geom_histogram(mapping = aes(x=carat), binwidth = .5)

## Count the cut width in .5 intervals##

diamonds %>%
  count(cut_width(carat,.5))

## Create a variable that has a smaller cut of diamonds, less than 3 carats to be exact

smaller <- diamonds %>%
  filter(carat <3)

## Plot those smaller carrots in a histogram with a binwidth of .1

ggplot(data = smaller, mapping = aes(x=carat)) +
  geom_histogram(binwidth = .1)

## If you want to overlay multiple histograms use the geom_freqpoly

ggplot(data = smaller, mapping = aes(x=carat, color=cut)) +
  geom_freqpoly(binwidth=.1)

## Notice a strange pattern in the following plot? Why does the carat peak in crating intervals? 

ggplot(data = smaller, mapping = aes(x=carat)) +
  geom_histogram(binwidth = .01)

## Notice the strange valley in the old faihtful eruption times? 

ggplot(data = faithful, mapping = aes(x=eruptions)) +
  geom_histogram(binwidth = .25)

### UNUSUAL VALUES ###
### OUTLIERS ARE DATA POINTS THAT DON'T SEEM TO FIT A PATTERN ###

## When outliers are difficult to see, make the x into the y

ggplot(diamonds) +
  geom_histogram(mapping = aes(x=y), binwidth = .5)

## When rare variables are hard to see, use coor_catesian to see them

ggplot(diamonds) +
  geom_histogram(mapping = aes(x=y), binwidth = .5) +
  coord_cartesian(ylim = c(0,50))

## Filter out diamond outliers (aka diamonds can't have a negative length and only billionaires can afford diamonds longer than an inch)

unusual <- diamonds %>%
  filter(y<3 | y>20) %>%
  arrange(y)
```

## MISSING VALUES

```{r}
## If you want to drop the entire row with the strange vaues (not recommended)

diamonds2 <- diamonds %>%
  filter(between(y,3,20))

## Instead use this method to replace the strange values by using the mutate function

diamonds3 <- diamonds %>%
  mutate(y=ifelse(y<3 | y>20,NA,y))

## Plot the new data ## Use NA.RM to remove missing values warning

ggplot(data = diamonds3, mapping = aes(x=x,y=y))+
  geom_point(na.rm = T)

## You may even want to make observations of missing variables, in this example if a departure time is na, we assume the flight has been cancelled

nycflights13::flights %>%
  mutate(
    cancelled = is.na(dep_time),
    sched_hour = sched_dep_time %/%100,
    sched_min = sched_dep_time %%100,
    sched_dep_time = sched_hour + sched_min /60
  ) %>%
  ggplot(mapping=aes(sched_dep_time)) +
    geom_freqpoly(
      mapping = aes(color=cancelled),
      binwidth = 1/4
    )
```

## COVARIATION

```{r}
## Variation describes behavior within a variable, Covariation describes behavior between variables

## Covariation is the tendency for two or more variables to vary together in a related way, in thos plot we will relate diamond prices to quality

ggplot(data = diamonds, mapping = aes(x=price)) +
  geom_freqpoly(mapping = aes(color=cut), binwidth = 500)

## Make distribution easier to see

ggplot(diamonds) +
  geom_bar(mapping = aes(x=cut))

## Display density to make it easier to see price across cuts

ggplot(
  data = diamonds,
    mapping = aes(x=price, y= ..density..)
  ) +
    geom_freqpoly(mapping = aes(color=cut), binwidth=500)

## Use a boxplot to give us a better look

ggplot(data = diamonds, mapping = aes(x=cut,y=price)) +
  geom_boxplot()

## The diamond data is counterintuitive, suggesting less quality diamonds are more expensive on average, lets look at class data in the MPG data

ggplot(data = mpg, mapping = aes(x=class, y=hwy)) +
  geom_boxplot()

## To make the trend easier to see, reorder the class based on the median value

ggplot(data = mpg) +
  geom_boxplot(
    mapping = aes(
      x=reorder(class, hwy,FUN = median),
      y=hwy
    )
  )

## If you have long variable names, flip the box 90 Degrees

ggplot(data = mpg) +
  geom_boxplot(
    mapping = aes(
      x=reorder(class, hwy,FUN = median),
      y=hwy
    )
  ) +
  coord_flip()
```

## TWO CATEGORICAL VARIABLES

```{r}
## To visualize covariation between two variables, you will need to count the number of observations for each combination

ggplot(data = diamonds) +
  geom_count(mapping = aes(x=cut,y=color))

## You can also compute the count with dplyr

diamonds %>%
  count(color, cut)

## Visualize with tiles

diamonds %>%
  count(color,cut) %>%
  ggplot(mapping= aes(x=color,y=cut)) +
    geom_tile(mapping = aes(fill=n))

###For better heatmaps, try the d3heatmap or heatmaply packages
```

## TWO CONTINOUS VARIABLES

```{r}
## Geom_point is a great way to see covariation between two coninous variables

ggplot(data = diamonds) +
  geom_point(mapping = aes(x=carat, y=price))

## With too much data, scatterplots become too difficult to see, use 'alpha' for transparency

ggplot(data = diamonds) +
  geom_point(
    mapping = aes(x=carat, y=price),
    alpha = 1/100
    )

## Geom_histogram and geom_freqpoly bin on one dimension, but geom_bin2d and geom_hex will allow you to bin in 2 dimensions

ggplot(data = smaller) +
  geom_bin2d(mapping = aes(x=carat, y=price))

## Or/and

ggplot(data = smaller) +
  geom_hex(mapping = aes(x=carat, y=price))

## If continous variables act like categorical variables, use categorical techniques

ggplot(data = smaller, mapping = aes(x=carat,y=price)) +
  geom_boxplot(mapping = aes(group = cut_width(carat,.1)))

## To make the box width proportional to the points in that box use 'cut_number'

ggplot(data = smaller, mapping = aes(x=carat,y=price)) +
  geom_boxplot(mapping = aes(group = cut_number(carat,20)))
```

## PATTERNS AND MODELS

```{r}
## Always be looking for patterns and clues in your dat to discover relationships, take the earlier old faithful example for instance

ggplot(data = faithful) +
  geom_point(mapping = aes(x=eruptions, y=waiting))

## The following develops a model for diamonds data, by fitting a model that predicts price from carat and then computes residuals (the difference betweenthe predicted value and actual value)

mod <- lm(log(price) ~ log(carat), data = diamonds)

diamonds4 <- diamonds %>%
  add_residuals(mod) %>%
  mutate(resid = exp(resid))

ggplot(data = diamonds4) +
  geom_point(mapping = aes(x = carat, y= resid))

## View boxplot

ggplot(data = diamonds4) +
  geom_boxplot(mapping = aes(x = cut, y = resid))
```

## GGPLOT2 CALLS

```{r}
## ggplot(data = faithful, mapping = aes (x=eruptions)) +
##    geom_freqpoly(binwidth = .25)

# Can be rewriten as

## ggplot(faithful,aes(eruptions)) +
##    geom_freqpoly(binwidth = .25)

# If we want to end a pipeline in a plot we can write it as below

## diamonds %>%
##    count(cut,clarity) %>%
##    ggplot(aes(clarity,cut,fill=n)) +
##      geom_tile()

# Unfortunately, Piping was created after ggplot2, so we still have to use the '+' instead of %>%
```

### Recommended Books:
####    - R Graphics Cookbook by Winston Chang
####    - Graphical Data Analysis by Antony Unwin